{
 "title": "Genera-PR",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "select data_fecha_acualizado as time, desc, value from Metrics;",
     "rawQueryText": "select data_fecha_acualizado as time, desc, value from Metrics;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "% Without Service",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  time,\n  name AS \"metric\",\n  percentage_clients_without_service AS \"% Out\"\nFROM\n  RegionData\nWHERE\n time between $__from/1000 AND $__to/1000\n group by time, name",
     "rawQueryText": "SELECT\n  time,\n  name AS \"metric\",\n  percentage_clients_without_service AS \"% Out\"\nFROM\n  RegionData\nWHERE\n time between $__from/1000 AND $__to/1000\n group by time, name",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Clients Per Region",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  time,\n  name AS \"metric\",\n  total_clients_with_service AS \"Total Clients With Service\"\nFROM\n  RegionData\nWHERE\n time between $__from/1000 AND $__to/1000\n group by time, name\n ORDER BY time asc\n",
     "rawQueryText": "SELECT\n  time,\n  name AS \"metric\",\n  total_clients_with_service AS \"Total Clients With Service\"\nFROM\n  RegionData\nWHERE\n time between $__from/1000 AND $__to/1000\n group by time, name\n ORDER BY time asc\n",
     "timeColumns": [
      "time",
      "Region",
      "name"
     ]
    }
   ]
  },
  {
   "title": "Percentage Of Clients Without Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 15 },
   "targets": [
    {
     "queryText": "SELECT\n  time,\n  name AS \"metric\",\n  percentage_clients_without_service AS \"Percentage Without Service\"\nFROM\n  RegionData\nWHERE\n time between $__from/1000 AND $__to/1000\n group by time, name",
     "rawQueryText": "SELECT\n  time,\n  name AS \"metric\",\n  percentage_clients_without_service AS \"Percentage Without Service\"\nFROM\n  RegionData\nWHERE\n time between $__from/1000 AND $__to/1000\n group by time, name",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Total Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "queryText": "SELECT \n    data_fecha_acualizado AS time,\n    sum(site_total) as mw\nFROM \n    LoadPerSite\ngroup by time;",
     "rawQueryText": "SELECT \n    data_fecha_acualizado AS time,\n    sum(site_total) as mw\nFROM \n    LoadPerSite\ngroup by time;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Total Generation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "queryText": "SELECT \n    data_fecha_acualizado AS time,\n    CAST(value AS REAL) AS mw\nFROM \n    Metrics\nwhere \"desc\" = 'Total de Generación'\nGROUP BY \n    data_fecha_acualizado;",
     "rawQueryText": "SELECT \n    data_fecha_acualizado AS time,\n    CAST(value AS REAL) AS mw\nFROM \n    Metrics\nwhere \"desc\" = 'Total de Generación'\nGROUP BY \n    data_fecha_acualizado;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Fuel Cost Over TIme",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "queryText": "SELECT \n    data_fecha_acualizado AS time,\n    AVG(value) AS average_fuel_cost\nFROM \n    FuelCost\nGROUP BY \n    data_fecha_acualizado\nORDER BY \n    time;",
     "rawQueryText": "SELECT \n    data_fecha_acualizado AS time,\n    AVG(value) AS average_fuel_cost\nFROM \n    FuelCost\nGROUP BY \n    data_fecha_acualizado\nORDER BY \n    time;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Average Fuel Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "Total Generation By Fuel Type",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT \n    fuel,\n    SUM(value) AS total_value\nFROM \n    ByFuel\nGROUP BY \n    fuel;",
     "rawQueryText": "SELECT \n    fuel,\n    SUM(value) AS total_value\nFROM \n    ByFuel\nGROUP BY \n    fuel;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}